version: '3.8'

networks:
  shared-network:
    driver: bridge
  sandbox_sandbox-shared-network:
    driver: bridge
    external: true

services:

  zipkin:
    container_name: zipkin
    networks:
      - shared-network
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  algosearch-backend:
    container_name: algosearch-backend
    networks:
      - shared-network
      - sandbox_sandbox-shared-network
#    image: ../docker/dockerfile.algosearch-backend
    image: kevguy/algosearch-backend:latest
    ports:
      - 5000:5000 # CRUD API
      - 4000:4000 # DEBUG API
    depends_on:
      - zipkin
      - algosearch-db

  algosearch-frontend:
    container_name: algosearch-frontend
    networks:
      - shared-network
      - sandbox_sandbox-shared-network
#    image: ../docker/dockerfile.algosearch-frontend
    image: kevguy/algosearch-frontend:latest
    ports:
      - 3000:3000
    depends_on:
      - algosearch-backend

  algosearch-metrics:
    container_name: algosearch-metrics
    networks:
      - shared-network
      - sandbox_sandbox-shared-network
#    image: ../docker/dockerfile.metrics
    image: kevguy/algosearch-metrics:latest
    ports:
      - 3001:3001 # EXPVAR API
      - 4003:4003 # DEBUG API
    depends_on:
      - algosearch-backend

  algosearch-db:
    image: couchdb:3.2.0
    container_name: "algorand-sandbox-couchdb"
    hostname: couchdb.server
    networks:
      - shared-network
      - sandbox_sandbox-shared-network
    ports:
      - 5984:5984
    # Optional
    # volumes:
    #   - ./db-data:/opt/couchdb/data
    # extra_hosts:
    #   - "dockerhost:$DOCKERHOST"
    # https://github.com/apache/couchdb-docker/issues/55
    #    command: curl -u admin:password -X PUT 128.0.0.1:5984/_users && curl -u admin:password -X PUT 127.0.0.1:5984/test
    # command: curl -u algorand:algorand -X PUT http://128.0.0.1:5984/_users && curl -u algorand:algorand -X PUT http://127.0.0.1:5984/algo_global
    environment:
      - COUCHDB_USER=algorand
      - COUCHDB_PASSWORD=algorand
